### ISSUE TITLE
forbids field for conflicting dependencies

### ISSUE THREAD

**Issue by mosteo** [alire-project/alire#105]
Alire releases can specify a set of forbidden dependencies, that are known to be conflicting (e.g., they contain sources with the same filename).

There's no current mention to this in the index syntax. In essence, that would be a key like depends_on:
```
[depends-on]
foo="^1.0"
[conflicts-with]
bar="~1.4"
```

The original use case was for Matreshka, which brings its own dependencies that can be already in alire, and were not easy to extricate. Although, long term, that should not happen, I guess this is a feature that can come in handy in the short term, and maybe for unforeseen conflicting circumstances.

Pinging @pmderodat for awareness (and can you think of other reasons for conflicts that are not name clashes?)

**Comment by pmderodat** [comment]
Oh, I did not notice this when creating the TOML index. I think this is a useful feature, if only because I don’t think it’s reasonable to assume that all crates in the index have no unit name in common: we could imagine two projects using the same name (they’ll have different crate name, but same Ada package names) or maybe even one crate containing a child package which is later integrated in a future release of the crate that contains the parent package.

**Comment by mosteo** [comment]
Re-enabled in #781.
