### ISSUE TITLE
add Gnu savannah as a trusted site

### ISSUE THREAD

**Issue by stephe-ada-guru** [alire-project/alire#1084]
I'm hoping to publish the Ada code required for Emacs ada-mode executables via Alire. The code is hosted at http://savannah.nongnu.org/projects/ada-mode, which is not in the Alire list of trusted sites. What is needed to declare it trusted?

**Comment by mosteo** [comment]
Hello Stephen, you could submit a PR with the change to `alire-publish.adb:52` but since this is a trivial modification we can do it directly.

Meanwhile, be aware that you can also [publish using a tar/zip file stored anywhere](https://alire.ada.dev/docs/#detailed-steps), in case you don't want to wait (as this change won't be generally usable until we publish a new version).
