### ISSUE TITLE
Is there some way to reference an externally built library project?

### ISSUE THREAD

**Issue by pmunts** [alire-project/alire#1305]
I would like to somehow use the prebuilt Debian 11 AWS library (only in conjunction with the Debian 11 compiler, of course).

I have confirmed that copying `/usr/share/gpr/aws.gpr` to `config/` and adding `with "aws.gpr";` to `config/xxxx_config.gpr` works perfectly.

Is it possible to define a crate that does not contain any source code, just a `.gpr` file for an externally built library project?

**Comment by pmunts** [comment]
To answer my own question, yes, you can create a crate containing nothing but aws.gpr.  It works perfectly for using the AWS library in the Debian distribution.

**Comment by mosteo** [comment]
I'm turning this into a discussion.

Isn't what you ask essentially what an external crate definition will get you?

Also note that Ada packages in Debian are expected to be used with the system compiler; otherwise .ali files won't match and try to cause recompilations for sources that are unavailable (IIRC from experiences long ago).
