### ISSUE TITLE
Alr build fails after "Run testsuite on selfbuilds too"

### ISSUE THREAD

**Issue by 0rzech** [alire-project/alire#1326]
When `alr build` is run on [887fd51](https://github.com/alire-project/alire/commit/887fd510a73abde34e0d4da6f36de7be1cf69381) (#1324), the build process fails with:
```
   [Ada]          clic-subcommand.adb
clic-config-edit.ads:1:20: error: file "toml.ads" not found
clic-config-edit.ads:1:20: error: "CLIC.CONFIG.EDIT (body)" depends on "CLIC.CONFIG.EDIT (spec)"
clic-config-edit.ads:1:20: error: "CLIC.CONFIG.EDIT (spec)" depends on "CLIC.CONFIG (spec)"
clic-config-edit.ads:1:20: error: "CLIC.CONFIG (spec)" depends on "TOML (spec)"

   compilation of clic-config-edit.adb failed

gprbuild: *** compilation phase failed
error: Command ["gprbuild", "-s", "-j0", "-p", "-P", "[redacted]/alire/alr.gpr"] exited with code 4
error: Compilation failed.
```

**Comment by mosteo** [comment]
#1324 itself contains a fix for this problem. In theory, if you build with `dev/build.sh`, and then use that for `alr build`, it should work.

Please reopen if this isn't working for you.

**Comment by 0rzech** [comment]
I don't have permissions to reopen this issue.

Suggested workaround does not help. Calling `alr build` after `dev/build.sh` gives the same error.

I wouldn't call this fix anyways, because it should work with `alr clean && alr build` cycle without specialized script calling `gprbuild` in the meantime.

**Comment by mosteo** [comment]
Well, in regard to the development branch, there is no guarantees that an older `alr` is going to be able to build it. That's why the instructions on building from sources say first to use `gprbuild` directly (no need for the script, it is there as a convenience to set `ALIRE_OS` for you).

If you still don't manage to build as described in https://github.com/alire-project/alire#building-from-sources , you can just add a `with "ada_toml.gpr"` line to the `clic.gpr` file. Which one, it'll depend on if you use `alr_env.gpr` or `alr build`; in `deps/clic` if the former or in `alire/cache/dependencies/clic_*` if the latter.

Hope this helps.

**Comment by 0rzech** [comment]
Thanks for your elaboration! My bad, the [README.md](https://github.com/alire-project/alire/blob/887fd510a73abde34e0d4da6f36de7be1cf69381/README.md) makes it clear I should use `gprbuild` directly. Somehow I got fixated on `alr build` regardless of `alr` version after seeing `alire.toml` in the repo. 😅
