### ISSUE TITLE
Wrong configuration files in dependencies

### ISSUE THREAD

**Issue by reznikmm** [alire-project/alire#1385]
The `alr` writes wrong configuration files for me in a dependencies (VSS). To reproduce:

* `alr index --add git+https://github.com/reznikmm/als-alire-index.git#v23.0.18 --name als`
* `alr get ada_language_server`
* in ada_language_server_23.0.18_973e7d46/alire/cache/dependencies/vss_24.0.0_9d3df28c/config
   * `vss_config.gpr` misses `-gnat2022` as it requested in VSS `alire.toml` with
     ```
     [build-switches]
     "*".ada_version = "Ada2022"
     ```
   * extra files `vss_config.ads` and `vss_config.h` - they are disabled in VSS `alire.toml` with 
     ```
     [configuration]
     generate_ada = false
     generate_c = false
     ```

**Comment by mosteo** [comment]
Which `alr` version is this? It could be related to #1355

**Comment by reznikmm** [comment]
alr 1.2.1

**Comment by mosteo** [comment]
OK, after closer inspection this isn't a bug. Alire relies on the manifest from the index, not the one that might be packaged with the sources (as otherwise crates could lie about what they're going to do once download, for example in actions). In fact, such a manifest is moved out of the way after deployment to `<crate>/alire/alire.toml.upstream` to avoid confusion about this.

So the problem is that the manifest at `~/.config/alire/indexes/als/repo/index/vs/vss/vss-24.0.0-20230529.toml` doesn't contain the switches you mention.

Same goes for the configuration extra files.

**Comment by reznikmm** [comment]
Thank you @mosteo ! Now I see my mistake. I changed `vss-24.0.0-20230529.toml` and it works now :gem: 

Sorry for the noise :pray:
