### ISSUE TITLE
Should '.cache/alire' be '.local/alire'?

### ISSUE THREAD

**Issue by mosteo** [alire-project/alire#1502]
Some say the former is for short-lived info and might even be mounted as tmpfs.

**Comment by atalii** [comment]
The XDG base directory spec does say that XDG_CACHE_HOME is for "non-essential" files. It seems that XDG_DATA_HOME (~/.local/share) is a better fit. Would a PR to use that be useful?

**Comment by mgrojo** [comment]
If we look at the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), the proper directory for "short-lived info and might even be mounted as tmpfs" is XDG_RUNTIME_DIR:

>  $XDG_RUNTIME_DIR defines the base directory relative to which user-specific non-essential runtime files and other file objects (such as sockets, named pipes, ...) should be stored. [..]
>
> The lifetime of the directory MUST be bound to the user being logged in. It MUST be created when the user first logs in and if the user fully logs out the directory MUST be removed. If the user logs in more than once he should get pointed to the same directory, and it is mandatory that the directory continues to exist from his first login to his last logout on the system, and not removed in between. Files in the directory MUST not survive reboot or a full logout/login cycle.
[..] Files in this directory MAY be subjected to periodic clean-up. To ensure that your files are not removed, they should have their access time timestamp modified at least once every 6 hours of monotonic time or the 'sticky' bit should be set on the file.
[..] Applications should use this directory for communication and synchronization purposes and should not place larger files in it, since it might reside in runtime memory and cannot necessarily be swapped out to disk. 

In this other [reference](https://wiki.archlinux.org/title/XDG_Base_Directory), there is even a mention of tmpfs only in the case of XDG_RUNTIME_DIR, and no one else.

A cache directory is for files that can be regenerated from another source, so users low on disk space may decide to clean up the cache used by the applications, but the system should not clean it automatically, because it will imply a degradation in performance on the next run of the application, which is the case if you delete the builds done by Alire.

On the other hand, XDG_DATA_HOME seems intended for essential files created by the applications on behalf of the user, and which cannot be regenerated from another source. Users should only delete this, knowing that they will lose the information.

In my opinion, the use of XDG_CACHE_HOME made by Alire is legitimate, and users putting this on tmpfs should know what it implies for the applications: continuous regeneration of their cached data.

**Comment by Fabien-Chouteau** [comment]
> users putting this on tmpfs should know what it implies for the applications: continuous regeneration of their cached data.

The problem is more with the limited size of a tmpfs cache that will lead to unexpected error messages.
In terms of user experience we should avoid this.

In my opinion, we should use either `XDG_DATA_HOME` or even `~/.alire/cache/`.

**Comment by mgrojo** [comment]
> > users putting this on tmpfs should know what it implies for the applications: continuous regeneration of their cached data.
> 
> The problem is more with the limited size of a tmpfs cache that will lead to unexpected error messages. In terms of user experience we should avoid this.

That's another reason for not putting `XDG_CACHE_HOME` under tmpfs. 

But I find references of recommendations to put `XDG_CACHE_HOME` under tmpfs, like these for using SSD from the [Gentoo wiki](https://wiki.gentoo.org/wiki/SSD). In my opinion, after reading the specification, it is that either those applications are doing something wrong or the recommendation is misguided (or both probably). There is already `XDG_RUNTIME_DIR` for those temporary files.

> In my opinion, we should use either `XDG_DATA_HOME` or even `~/.alire/cache/`.

Seen that it's not a particular user doing something wrong, but they were following published recommendations, I agree, it's better for Alire not to use that misunderstood location.

Others have fled from that directory for the same reason, even acknowledging it's wrong to place it on tmpfs. https://github.com/keepassxreboot/keepassxc/issues/9738

**Comment by mosteo** [comment]
Thanks for the valuable feedback, everyone. I'm now convinced that even if `XDG_CACHE_HOME` seemed the proper choice, the risk for misuse compels us to avoid it.

`.alire/` is expected to be a regular prefix resulting from `gprinstall`, so I don't like mixing our files with whatever can end up there. Thus I propose using `XDG_DATA_HOME`.
