### ISSUE TITLE
alr can't find libgcc_s.1.dylib

### ISSUE THREAD

**Issue by rogermc2** [alire-project/alire#1628]
Mac OSX 14.4
Xcode 15.1
which alr : /usr/local/bin/alr
alr version:
alr version:               2.0-rc1
libalire version:          2.0-rc1
compilation date:          2024-02-29 11:16:58
compiled with version:     13.2.0

All attempts to build any crate result in the following error.
I have tried reinstalling alire.
Making sure path to libgcc_s.1.dylib is in PATH
Copied libgcc_s.1.dylib into usr/local/lib

Building hello=1.0.2/hello.gpr...                                    
dyld[16109]: Library not loaded: /Users/runner/work/GNAT-FSF-builds/GNAT-FSF-builds/sbx/x86_64-darwin/gcc/install/lib/libgcc_s.1.dylib
  Referenced from: <B845D339-93DA-35CD-BFEB-5D2C3AC3F2C2> /Users/Roger/.local/share/alire/toolchains/gprbuild_21.0.2_4f77240c/bin/gprbuild
  Reason: tried: '/Users/runner/work/GNAT-FSF-builds/GNAT-FSF-builds/sbx/x86_64-darwin/gcc/install/lib/libgcc_s.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/GNAT-FSF-builds/GNAT-FSF-builds/sbx/x86_64-darwin/gcc/install/lib/libgcc_s.1.dylib' (no such file), '/Users/runner/work/GNAT-FSF-builds/GNAT-FSF-builds/sbx/x86_64-darwin/gcc/install/lib/libgcc_s.1.dylib' (no such file), '/usr/X11/lib/libgcc_s.1.dylib' (no such file)
error: Command ["gprbuild", "-s", "-j0", "-p", "-P", "/Volumes/MPLAB/Ada_Source/Adam/hello_1.0.2_5715870b/hello.gpr"] exited with code -1
error: Compilation failed.

**Comment by rogermc2** [comment]
This appears due, yet again, to Apple sabotaging their customers' work.
Under OSX 14.4, Terminal and Xcode both have full disk access.

Alire works fine under:
OSX High Sierra and  X_Code 10.1.

Any ideas on how to overcome OSX 14.4 limitations will be greatly appreciated.

**Comment by mosteo** [comment]
Pinging @simonjwright wisdom...

**Comment by simonjwright** [comment]
I can reproduce this. It happens on trying to run `gprbuild`.

The clue lies in the error message: when it says
```
dyld[16109]: Library not loaded: /Users/runner/work/GNAT-FSF-builds/GNAT-FSF-builds/sbx/x86_64-darwin/gcc/install/lib/libgcc_s.1.dylib
```
this is because the dynamic linker (dyld) is trying to load a dynamic library that `gprbuild` says it wants:
```
$ otool -L /Users/simon/.cache/alire/dependencies/gprbuild_22.0.1_b1220e2b/bin/gprbuild
/Users/simon/.cache/alire/dependencies/gprbuild_22.0.1_b1220e2b/bin/gprbuild:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.60.1)
	/Users/runner/work/GNAT-FSF-builds/GNAT-FSF-builds/sbx/x86_64-darwin/gcc/install/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```
(I found where Alire's copy of `gprbuild` is saved by `alr exec -- which gprbuild`).

Now, `/Users/runner/work/GNAT-FSF-builds/GNAT-FSF-builds/sbx/x86_64-darwin/gcc/install/` is the place on Github where GCC was built, and `libgcc_s.1.dylib` is built as part of GCC, and `gprbuild` was built against the libraries provided by GCC.

The default macOS behaviour with dylibs is that each dylib knows where it is in the filesystem, and executables linked against a dylib remember where the dylib is -- or, if you move the dylib, where it _was_, resulting in the behaviour we're seeing. It's possible to organise things to mitiigate this, and clearly macOS 14.3 manages to do this for us.

In the meantime, we can work round it by adding the actual library location to `dyld`'s search path (in `DYLD_LIBRARY_PATH`, **not** `LD_LIBRARY_PATH` or `PATH`).

If I say `alr exec -- which gcc`, I get
```
/Users/simon/.cache/alire/dependencies/gnat_native_13.2.1_c21501ad/bin/gcc
```
and what you want in your `.bash_profile` or `.zshrc` is
```
export DYLD_LIBRARY_PATH=/Users/simon/.cache/alire/dependencies/gnat_native_13.2.1_c21501ad/lib
```

Of course, this will change when you install a new version of `gnat_native`!

**Comment by rogermc2** [comment]
Thanks Simon.
I added to my .profile:
 export DYLD_LIBRARY_PATH=/Users/Roger/.local/share/alire/toolchains/gnat_native_12.2.1_77267eb1/lib

Now the simple hello example builds OK.
Do you have any idea of what has changed in OSX 14 to cause this problem?

**Comment by rogermc2** [comment]
This also fixes the problem. 
export DYLD_LIBRARY_PATH="/opt/GNAT/2020/lib"

**Comment by mosteo** [comment]
> Of course, this will change when you install a new version of `gnat_native`

Just dropping by to say that you can know that folder name with e.g. `alr get gnat_native --dirname`.

**Comment by simonjwright** [comment]
> Do you have any idea of what has changed in OSX 14 to cause this problem?

No. Normally you’d expect this sort of change to come with new releases of the SDK.

**Comment by rogermc2** [comment]
Thanks Simon,
That's a helpful comment from my point of view as it at least identifies the most likely part of the system that causes the problem.

**Comment by rogermc2** [comment]
An associated  problem has reoccurred under OSX High Sierra and X_Code 10.1 when using an elf toolchain.

dyld: lazy symbol binding failed: Symbol not found: ___darwin_check_fd_set_overflow
  Referenced from: /Users/rogermcmurtrie/.config/alire/cache/dependencies/gprbuild_21.0.2_4f77240c/bin/gprconfig (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ___darwin_check_fd_set_overflow
  Referenced from: /Users/rogermcmurtrie/.config/alire/cache/dependencies/gprbuild_21.0.2_4f77240c/bin/gprconfig (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

I'm not sure what's the best way of handling this.
get gnat_native --dirname returns
gnat_native_12.2.1_77267eb1.

**Comment by rogermc2** [comment]
This is not really a problem as I only intend using cross compiled code from OSX14.
