### ISSUE TITLE
GNAT 14.1.0 and RedHat 8.4

### ISSUE THREAD

**Issue by MrAda** [alire-project/alire#1689]
**Describe the bug**
I cannot link with the version of GNAT (or the prior version) under Redhat 8.4.  The glibc is wanting 2.29 and Redhat 8.x only goes to 2.28.

**To Reproduce**
1. Install 14.1.0 and compile/link a small program with Ada and C
2. See error

**Expected Behavior**
I expected my project to build like it did under RHEL 7.9. 
Also have issues with rpc (RHEL 7.9) with its replacement of libtirpc.so.3 which doesn't link AFAIK.

**`alr` version**
not necessary as I cannot use it in a closed environment.

**`alr` logs**
n/a

**Comment by Fabien-Chouteau** [comment]
Hello @MrAda, 

That's a common issue with binary distribution on Linux. It's not possible to compatible with every possible versions of every distribs because of the different libc versions. The only way would be to build for each and everyone, but that's not manageable in practice. If you cannot update to a more recent RedHat (with a more recent libc), then you either have to build GNAT yourself, or ask RedHat to provide it for you.

I am afraid there's not much we can do here.
