### ISSUE TITLE
Cross-compilation

### ISSUE THREAD

**Issue by mosteo** [alire-project/alire#19]
Of indexed projects, not of alr itself

**Comment by jklmnn** [comment]
I don't know if this should be in a separate issue or if the functionality is already available (at least I didn't find it). But not only cross compilation but also custom flags are an issue. We have a project that requires custom compiler flags (e.g. `-fPIC`) and configurations (library kind static) as it compiles the dependencies as static libraries and then includes them into a dynamic library. It would be nice to have a possibility to override certain options of the upstream gpr file (or at least require to make some options configurable via `external` but this might not be flexible enough). I think this is as important for embedded targets as cross compilation is.

**Comment by Fabien-Chouteau** [comment]
Hi @jklmnn ,

I think this will be one of the major challenge for the future of Alire. One of the problem here, in my opinion, is that gpr files do not provide a way to control the configuration/scenario-variables of the project dependency.

I actually have been thinking about this topic (and made some experiments: [ada-config-generator](https://github.com/Fabien-Chouteau/ada-config-generator) [metagpr](https://github.com/Fabien-Chouteau/metagpr)), but one of the open question for me is what tool should have the responsibility for this. Alire, Gprbuild, or something else?

**Comment by mosteo** [comment]
Some other thoughts: 

Overriding of dependency externals by dependents seems reasonable, but what if two dependents override the same dependency? Simple: err out. Complex: force an even more downstream dependent (or the user) to re-override. Other: ???

By experience with GPR, cumulative addition of compilation flags is not trivial. I think we better not reattempt something that gprbuild is already doing. OTOH, providing external definitions to select a configuration is already supported with `alr compile -X` switches and crate `gpr-set-externals`. What isn't supported (yet?) is to somehow force a crate/the user to define an external that has no default.

For the definition of cross-targets, my current vision is to have a rich-enough set of environment variables (currently we have compiler, os, word-size, distribution) that can be set simultaneously when specifying a target (e.g., `--target=XXX` sets these instead of the actual autodetection). But my experience with cross-compilation is minimal so I'm surely missing many things here.

**Comment by mosteo** [comment]
Cross-compilers are in the index and with crate configuration and build profiles, things are on track. So I'm closing this one.
