### ISSUE TITLE
Package development workflow

### ISSUE THREAD

**Issue by jklmnn** [alire-project/alire#240]
I started developing a package for Alire and initialized the repo with `alr init --lib --in-place <name>`. I noticed that adding a dependency requires a version to be set, yet a version doesn't exist yet in this project. So I created the entry for the next version but it required an origin. Since I didn't create a release yet on GitHub I could only set the origin to something, e.g. the master tarball. But even then there is a circular dependency as I can never have the version in the toml file in the repo and the actual release on GitHub in a consistent state as I would have to guess the hash for the release tarball before crafting the release.
I then looked into other project and noticed that they didn't incorporate the alire directory into the source tree. I wonder what the desired workflow is then as the only developer provided information seems to be the toml file in the index?
I somehow miss the functionality to develop (and in this process specify dependencies) and then to publish (an already created) release independently.

**Comment by mosteo** [comment]
You're right that this is an area that is sorely lacking information (and automation). Even so, I think it should be doable without circularities. I will prepare some instructions ASAP.

**Comment by pmderodat** [comment]
Any news on this? I stumbled on the same issue. :-) Thanks!

**Comment by mosteo** [comment]
Ooops this had been buried in my to-do stack. Thanks for the heads-up.

**Comment by mosteo** [comment]
I think I'm missing some piece of the puzzle. @jklmnn, if I understand correctly you want to develop in an unreleased project, while using dependencies from alire. At a later time you might want to publish this development with a proper version. This is what I did to tests this use case:

1. `alr init --bin xxx` (This should be equivalent to your in-place initialization)
1. `alr with libhello`
   - This adds a dependency on libhello. The `alire/xxx.toml` file is modified accordingly by `alr` (you could do this manually if you prefer). 

Your working release (`xxx` here) has version 0.0.0 when initialized. This does not really matter (yet). 

I may be missing something obvious. The *"I noticed that adding a dependency requires a version to be set, yet a version doesn't exist yet in this project"* is throwing me away. The version is needed once you want to publish your release, but not yet. 

If I'm following correctly, after the above steps let's say you want to publish xxx v1.0. At that time, in essence, you need to take the `alire/xxx.toml` file and use it as the basis for the PR you'd submit to the index. It's then when you can replace the 0.0.0 version with the proper one, and the filesystem origin with the online URL of the zipped `xxx` (without the `alire` folder, which is recreated on download by `alr`) (we may need a toml pretty-printer at some point to help with this).

Please let me know if this helps.

**Comment by pmderodat** [comment]
Hello @mosteo, thanks for having a look!

I have the feeling @jklmnn’s question considers instead adding dependencies to unreleased crates. (correct me if I’m wrong!) In your example, you add a dependency on `libhello`’s last version, and that works just fine today. The problem comes when you are yourself working on `libhello` and have local modifications (i.e. changes not available in existing `libhello` releases).

IIUC, as of today you have to 1) create a source archive from your `libhello` local (and modified) checkout, 2) compute its hash 3) modify your index to point to this archive. This is quite involved, especially considering that you need to do it again as soon as you add new changes to `libhello`.

Instead, it would be handy to have a way to say to Alire:

1. When adding the dependency: “the origin is this directory in the filesystem” (i.e. not an archive, and thus the hash check is skipped)
2. After this dependency got new changes: “please update this dependency using its local origin”.

As a bonus: in the Python ecosystem, contributing to an existing project is in principle very easy:
1. Clone the project’s repository.
2. Run `pip install -r REQUIREMENTS`, where `REQUIREMENTS` is a text file inside this repository that states all the dependencies you need in order to work on the project.

Even though Alire makes it much easier than without a package manager, doing the same with Alire currently isn’t as handy: when contributing to a project, you generally don’t want to start from an existing release (which is what `alr get` will fetch), but from the current development branch. So you end up cloning the repository yourself. Then you have to run `alr init`, and add all dependencies one by one (manually providing the version constraints for each) in order to finally build the project. Being able to store a list of dependencies (+ version constraints) and getting Alire install them in one command would be nice! I’m mentionning that, in the event that we enhance Alire to satisfy the original problem, we can keep this related use case in mind. :-)

I hope this helps,

**Comment by mosteo** [comment]
Cursorily read because I'm really overloaded rn, but I see what you mean. Definitely that's a case I hadn't reached yet and that we need to address to make it as easy as possible.

Still, I think there's a slightly simpler way on what you describe, by defining a local index with the working dependency as a filesystem origin (a folder, not an archive), so you save the rezipping everytime (if you remember, at some point we discussed to use copies or soft-linking) and there's no integrity check. Probably something will be broken in the updating though as this is untested. Might be a temporary help, but definitely not the way to go. I'll practice what you describe for python, I have some idea also on how this is done in opam and cargo too.

**Comment by Fabien-Chouteau** [comment]
> Instead, it would be handy to have a way to say to Alire:
> 
>     1. When adding the dependency: “the origin is this directory in the filesystem” (i.e. not an archive, and thus the hash check is skipped)
> 
>     2. After this dependency got new changes: “please update this dependency using its local origin”.

My symlinks PR is a solution to that problem #288 (but only on UNIX).

I use it to develop a project that has 3 or 4 dependencies in progress.

**Comment by jklmnn** [comment]
@pmderodat yes that's what I had in mind (at least one aspect of what I had in mind). I also had some problems when developing on the application itself. But I can't exactly recall what exactly the problem was so I can't give a more comprehensive explanation for now.

> Still, I think there's a slightly simpler way on what you describe, by defining a local index with the working dependency as a filesystem origin (a folder, not an archive), so you save the rezipping everytime (if you remember, at some point we discussed to use copies or soft-linking) and there's no integrity check.

That would be quite helpful to have!

@mosteo I try to elaborate the problems I had initially when I opened this issue. Although I'm currently not working on something that would be suitable to test Alire with and I lack the time to do so. So it may take some time until I can elaborate further.

**Comment by mosteo** [comment]
> My symlinks PR is a solution to that problem #288 (but only on UNIX).

If we can make something like this portable I think it makes more sense for directories, since we already have local source archives for when copying in place is preferable. Still, not having to create an extra index would be handy.

**Comment by mosteo** [comment]
I was re-reading this thread and a couple of observations:

> Run pip install -r REQUIREMENTS, where REQUIREMENTS is a text file inside this repository that states all the dependencies you need in order to work on the project.

We have a way to do this via `alr with --from project.gpr`. This relies on comments such as:

> `with "rxada"; -- alr with rxada^1.0`

This could blend nicely with the latest comments from Fabien in #313; as we add the withs we can add the comment. Also, at packaging time, we could ensure that such comments exist/are created in the crate project file.

Or we could use a dedicated file a la REQUIREMENTS for more visibility, of course. This would already work as long as its contents are formatted as Ada comments as shown.

As for the current difficulty of having local working versions of dependencies, drawing inspiration from cargo/opam, if we use a lockfile (#251), it could be a simple matter of doing e.g.:

> `alr pin crate /path/to/crate/working/dir 

and that would override the dependency with a local folder.

**Comment by Fabien-Chouteau** [comment]
> We have a way to do this via `alr with --from project.gpr`. This relies on comments such as:
> > `with "rxada"; -- alr with rxada^1.0`
> This could blend nicely with the latest comments from Fabien in #313;

In the process of experimenting with #313 I was actually going to suggest we remove this feature :)
It is going to get confusing if these comments can be both written by the user and by `alr`.

> Or we could use a dedicated file a la REQUIREMENTS for more visibility, of course. This would already work as long as its contents are formatted as Ada comments as shown.

I prefer the REQUIREMENTS file or maybe add a `dev-dependencies` entry in the `.toml` of the crate.

> > `alr pin crate /path/to/crate/working/dir
> and that would override the dependency with a local folder.

It looks like a great solution to me!

It could even be a repo address and `alr` does the clone:
`alr pin crate https://github.com/Fabien-Chouteau/GESTE`

**Comment by mosteo** [comment]
> I prefer the REQUIREMENTS file or maybe add a dev-dependencies entry in the .toml of the crate.

I prefer the plain text file, so people can describe dependencies without writing a whole crate file. There may be people that don't want to bother at all with Alire packaging.

**Comment by mosteo** [comment]
This should be solved by changes merged in #505. Also #439 should be helpful at the moment to deal with in-progress versions, even if we are missing quality-of-life options like pinning a remote origin (#508).

As for making easier to contribute to an upstream project, now one can distribute sources with a bundled `alire.toml` file and running `alr update` should be enough to get going. 

I'm closing for now, please reopen if you still see shortcomings with the new features.
