### ISSUE TITLE
Use configuration values for new crates (email, name, login, etc.)

### ISSUE THREAD

**Issue by Fabien-Chouteau** [alire-project/alire#455]
I found the code where this needs to go but `Alire.Releases` is pre-elaborate so it cannot depend on `Alire.Config`: 
https://github.com/alire-project/alire/blob/738e4b43cf696f5c387ed3b313390ad189d99428/src/alire/alire-releases.adb#L42

**Comment by Fabien-Chouteau** [comment]
We could also prompt the user for those info when they are not in the config already.

**Comment by mosteo** [comment]
There's the nuclear option of abandoning explicit preelaboration everywhere; for such a big/complex thing like libalire I'm doubtful about any advantages, since parts of the library can't be preelaborable anyway. I've read comments from some ARG lawyers saying that preelaboration pragmas are a broken idea but we're stuck with it. Frankly this is one of these things that irk me about Ada. 

A workaround I've used for this kind of situation in the past is to set up a hook during initialization into a preelaborable package. It's pure code noise though.

**Comment by Fabien-Chouteau** [comment]
Now would be the best time to remove all preelaboration. Do you remember why it was required in the first place?

**Comment by Fabien-Chouteau** [comment]
I did a ``sed -i 's/with Preelaborate //g' on all sources and it seems to be ok. Compiles and testsuite clean.

**Comment by mosteo** [comment]
>  Do you remember why it was required in the first place?

No need in the case of Alire, but that I try to mark everything that's Pure/Preelaborable as such. I guess we lose nothing down the road with half the packages not being preelaborable already.

**Comment by Fabien-Chouteau** [comment]
> I did a ``sed -i 's/with Preelaborate //g' on all sources and it seems to be ok.

Actually it's not when doing a full re-build.

**Comment by Fabien-Chouteau** [comment]
@mosteo can we provide the user info to the sub-program that create the release in `alr init`?
I tried to follow the callstack but I am not sure what is there to change.

**Comment by mosteo** [comment]
> @mosteo can we provide the user info to the sub-program that create the release in `alr init`?
> I tried to follow the callstack but I am not sure what is there to change.

I realize I didn't see/forgot this ping from you, my apologies. As we said this morning I'll try to pick up #461 to use these values during init.

**Comment by mosteo** [comment]
Implemented in #548.
