### ISSUE TITLE
alr show does not show which dependencies are unresolved

### ISSUE THREAD

**Issue by onox** [alire-project/alire#646]
`alr show <crate>` shows a list of dependencies, but does not show which of those are unresolved.

Tested with `alr show sdlada` on Arch Linux.

I ran `alr show --external libsdl2` and it shows empty details for Arch, but Available is True :confused: 

If I use `alr show --solve sdlada` it shows:

```
Dependencies (direct):
   gnat/=2020
   libsdl2^2.0
   libsdl2_image^2.0
   libsdl2_ttf^2.0
Dependencies (solution):                                                    
   gnat=10.2.0
Dependencies (external):
   libsdl2^2.0 (direct,hinted)
   libsdl2_image^2.0 (direct,hinted)
   libsdl2_ttf^2.0 (direct,hinted)
Dependencies (graph):
   sdlada=2.3.1 --> gnat=10.2.0 (/=2020)
   sdlada=2.3.1 --> libsdl2^2.0         
   sdlada=2.3.1 --> libsdl2_image^2.0   
   sdlada=2.3.1 --> libsdl2_ttf^2.0     
Dependencies cannot be met
```

with `hinted` in yellow. Does that mean it could not find the package?

**Comment by mosteo** [comment]
Yes, anything shown as "hinted" is known to be available in some platform (not necessarily the current one), but not detected.

Anything listed under external when using `--solve` is missing. Another clear indication that something is missing is that the rhs in the graph arrow shows a dependency instead of the resolved version. 

Now that you point it out, this is a nomenclature mix-up, as that "external" in `alr show` should indeed be "missing". Externals mean another thing internally (that there are detectors for releases not packaged in source form). After solving, a crate may be missing or not, no matter if it comes from a regular release or external definition.

> I ran alr show --external libsdl2 and it shows empty details for Arch, but Available is True :confused:

The output of `show` for regular releases and externally-defined ones is different. That Available means that the external definition is available on your platform (i.e., that it will be attempted by the solver), not that a release is available. So it's kind of an "enabled" flag in this case. Since the Arch line is empty, that means that no system package has been defined for detection, and it will never be found. I'm realizing how confusing this is.

The current modes of `show` are:

- For regular (source) releases:
   - `alr show` lists top-level dependencies, without attempting to solve them.
   - `alr show --solve|--tree` appends the result of calling the solver on the dependencies.
- For crates with only external definitions (like `libsdl2`):
   - `alr show` just warns that external definitions exist.
   - `alr show --external` lists the external definitions, without attempting to detect them.
   - `alr show --external-detect` lists the result of running the external detection (if successful, the output will be similar to `alr show` with the info of the detected release).

From your feedback I see several potential changes to clarify what's being shown. One is the "Available" header. Another is that `alr show --external` might be the default for external-only crates (i.e., no `--external` needed).

This is based on a principle of minimum action, as detection can be time consuming. We could instead try to detect by default and disable detection on demand.

**Comment by Fabien-Chouteau** [comment]
@mosteo Is there still something you want to do with this one?

**Comment by mosteo** [comment]
I wanted to simplify all the internal missing, hinted, external, etc into user-facing plain unresolved  to avoid confusion. But it's not a clean change to do, I'm afraid, and it will break several tests.

**Comment by Fabien-Chouteau** [comment]
For me there are two problems:

1. "Hinted" is really difficult to understand in my opinion. I am not even sure we should keep this feature.
2. Showing solved and missing dependencies all together. Users have should be able understand immediately what is missing and why.

For instance in solution changes, we could make it 2 categories (Solved, Missing):
```
   New solution is incomplete.
   +  sdlada               2.3.1  (new)
   +  make                  9.9.9 (new, .......)
   
   The following dependencies are missing:
   + this_crate_does_not_exist  ....
   +🔎 libsdl2              ^2.0   (new,external,indirect)
```

**Comment by mosteo** [comment]
Yeah, I've said the same elsewhere about "hinted". The original purpose was to give some instructions/URL to be able to find/install manually that dependency. That could be kept internally, but the user needs not know the difference. We have only a couple dependencies using hints in a really useful way.

Separating into two blocks should be easy to do.

**Comment by Fabien-Chouteau** [comment]
It's going to be for v3.0, but we may drop all externals except for system package.

With system package manager for retrieval and pkg-config for build flags.
