### ISSUE TITLE
Use of templates

### ISSUE THREAD

**Issue by pmderodat** [alire-project/alire#88]
Hello @mosteo 

Opening this issue to keep track of your answer, and potentially to track the work involved.

The index was migrated to TOML files and you are currently working on migrating “data” files that `alr` creates when checking out/building projects to TOML files as well. Does that mean that soon templates will become obsolete?

This would mean that we’ll be able to reduce the amount of files that `alr` needs to download in order to work to just the index, and that would be great!

Note that I would be interested in contributing to this, if only because this would simplify my work on #5. Thanks!

**Comment by mosteo** [comment]
Well, not really since templates right now are used for the skeleton .gpr and .ad? files used by `alr init`, and those are unrelated to the TOML project file. 

That part needs reworking anyway to make it portable to windows (now it's done by `grep`ing the source templates). 

In the distant past I used the Ada Web Server resource compiler that allows embedding files directly in the code during compilation (or was it part of Templates_Parser?). That could be a way, although that complicates the build by requiring more than a mere `gprbuild` command.

Any other ideas?

**Comment by pmderodat** [comment]
Ah, I see, thanks! I’ve never used AWS’ template_parser, but something that would embed templates in the program itself would be convenient.

Keeping `alr` buildable with a single gprbuild command looks worthwhile. I don’t expect templates to change very often, so I would suggest to track Ada sources generated from them in the repository (much like configure scripts from autotools) and regenerate them manually when needed (i.e. when someone modifies them). That would sound like a good compromise. What do you think?

(FYI, if we reach consensus, I would be interested in working on that at some point :-))

**Comment by mosteo** [comment]
It seems very sensible to me. Templates_Parser also has very nice ways of filling in placeholders from Ada, so it would suit us perfectly.

I'm in no hurry of changing this part so you can tackle it at your leisure.

**Comment by mosteo** [comment]
Finally done without templates in #126.
